apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-app-dev
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: coffee-app
      version: dev
  template:
    metadata:
      labels:
        app: coffee-app
        version: dev
    spec:
      containers:
      - name: coffee-app
        image: tejasprabhu/coffee-project-${REPO}:${IMAGE_TAG}
        ports:
        - containerPort: 3000
