apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-app-canary
spec:
  replicas: ${CANARY_REPLICAS}
  selector:
    matchLabels:
      app: coffee-app
      version: canary
  template:
    metadata:
      labels:
        app: coffee-app
        version: canary
    spec:
      containers:
      - name: coffee-app
        image: tejasprabhu/${REPO_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 3000
